### PR TITLE
Start learning page

### PR DESCRIPTION
**Pull request by Omoruyis**
https://omoruyis.github.io/start2/

### CODE REVIEW

**Comment by Ezeko** [comment]
rename it to be the the name of the page. REGISTER.html

**Comment by Omoruyis** [comment]
I've renamed it

**Comment by Eronmmer** [comment]
There are still conflicts

**Comment by Omoruyis** [comment]
There's conflict because I renamed the file
That's the conflict

**Comment by Omoruyis** [comment]
Don't worry, I'd just make a new branch and make a pull request

**Pull request closed without merging**
