### PR TITLE
Footer - Start button

### PR DESCRIPTION
**Pull request by siyfa**
Enable the start button at the footer of all the pages to lead to register page. Make necessary adjustment  on some pages footer that are not align with the rest.

### CODE REVIEW

**Comment by serignoleba** [comment]
link to test

**Comment by siyfa** [comment]
Total forgot. Sorry about that.
here it is https://startng.netlify.com

**Comment by serignoleba** [comment]
Fix the conflicts

**Comment by siyfa** [comment]
Conflict solved.

**Comment by serignoleba** [comment]
Still one more conflict check

**Comment by siyfa** [comment]
Now, there are no conflict. I don't know why later a conflict will happen.

**Comment by serignoleba** [comment]
The search.html is the conflicting file, fix it and get back to me

**Pull request merged**
