### PR TITLE
individual course page 3

### PR DESCRIPTION
**Pull request by Fatimah019**

### CODE REVIEW

**Comment by phiiileo** [comment]
Link for testing

**Comment by Fatimah019** [comment]
https://charlene04.github.io/Individual-Course-Page/individual_course.html

Page URL

**Comment by fabianuzukwu** [comment]
the styling of the email box is not encouraging , the background pictures are blur..

**Comment by charlene04** [comment]
The background picture is what we could get from the figma design sir..

**Comment by charlene04** [comment]
Asides the email input styling, is there any other major change that is
required?

**Comment by fabianuzukwu** [comment]
the fonts....

**Comment by charlene04** [comment]
Honestly, all you've stated except the email input, is according to design
on figma..

**Pull request closed without merging**
